# issuer: reviewer
richimf:
  - YoSoyIsma
# you can set multiple reviewers
davidrmh:
  - davidrmh
  # - casbrot
# you can use regexp to match issuer
# john.*:
#   - foo
#   - bar
# fallback
.*:
  - YoSoyIsma
  - davidrmh
  - casbrot