# Github action for Pull Request validations
name: Pull Request Check

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:  
  # Reviewers assignation
  reviewers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Reviewers
        if: github.event.pull_request.edited
        uses: uesteibar/reviewer-lottery@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
        # uses: shufo/auto-assign-reviewer-by-issuer@v1.0.0
        # with:
        #   config: '.github/auto_assign.yml'
        #   token: ${{ secrets.GITHUB_TOKEN }} 
