# Github action for Pull Request validations
name: Pull Request Check

on:
  pull_request:
    types: [opened, edited, reopened, synchronize, ready_for_review]

jobs: 
  # Title validation 
  title-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: seferov/pr-lint-action@master
        if: github.event.action != 'review_requested' && github.event.action != 'edited' && github.event.action != 'reopened' && github.event.action != 'synchronize' && github.event.pull_request.draft == false
        with:
          title-regex: '^(?:\[IMPROVEMENT\]|\[FEATURE\]|\[BUGFIX\])\[([A-Z])+\-(\d+)\]\s(\w){1,}(\w|\s|\-|\.|\,|\:|\;){1,}$'
          error-message: '*** Pull Request does not follow the Jira Format: [TYPE][JIRA-ID] Title description ***'
#   # Reviewers assignation
#   reviewers-qa:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: shufo/auto-assign-reviewer-by-issuer@v1.0.0
#         if: github.event.pull_request.draft == true
#         with:
#           config: '.github/auto_assign.yml'
#           token: ${{ secrets.GITHUB_TOKEN }}
