name: "Reviewer lottery"
on:
  pull_request:
    types: [opened, ready_for_review, reopened]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: uesteibar/reviewer-lottery@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}

# name: 'Auto Assign'
# on: pull_request

# jobs:
#   add-reviews:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: kentaro-m/auto-assign-action@v1.1.2
#         with:
#           configuration-path: ".github/auto_assign.yml"