
# Github action for Pull Request validations
name: Pull Request Check

on:
  pull_request:
    types: [opened, edited, reopened, synchronize, ready_for_review]

jobs: 
  # Pull Request title validation format
  title-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: seferov/pr-lint-action@master
        with:
          title-regex: '^(?:\[IMPROVEMENT\]|\[FEATURE\]|\[BUGFIX\])\[([A-Z])+\-(\d+)\]\s(\w){1,}(\w|\s|\-|\.|\,|\:|\;|\/|\\){1,}$'
          error-message: '*** Pull Request does not follow the Jira Format: [TYPE][JIRA-ID] Title description ***'
  # Reviewers assignation
  reviewers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set the Reviewers
        # Devs
        uses: uesteibar/reviewer-lottery@v1
        if: ${{ github.event_name == 'ready_for_review' }}
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
        # QA
      - uses: shufo/auto-assign-reviewer-by-issuer@v1.0.0
        if: ${{ github.event_name == 'ready_for_review' }}
        with:
          config: '.github/qareviewers.yml'
          token: ${{ secrets.GITHUB_TOKEN }}


