name: "Auto Assign"
on:
  pull_request:
    types: [opened, ready_for_review, reopened]

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
    - uses: shufo/auto-assign-reviewer-by-issuer@v1.0.0
      with:
        config: '.github/reviewers.yml'
        token: ${{ secrets.GITHUB_TOKEN }}